#version: "3.9"

services:
  mariadb:
    build: ./requirements/mariadb
    restart: always
    env_file:
      - ../secrets/.env
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress
    restart: always
    env_file:
      - ../secrets/.env
    depends_on:
      - mariadb
    networks:
      - backend
    volumes:
      - wordpress_data:/var/www/html
  nginx:
    build: ./requirements/nginx
    restart: always
    ports:
      - "443:443"
    env_file:
      - ../secrets/.env
    depends_on:
      - wordpress
    networks:
      - backend
    volumes:
    - wordpress_data:/var/www/html:ro
    - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
volumes:
  nginx:
  mariadb_data:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/gnicolo/data/wordpress

networks:
  backend:
